name: Build

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser typescript ts-loader terser-webpack-plugin

      - name: Build
        run: npm run tsc